# -*- coding: utf-8 -*-
from south.utils import datetime_utils as datetime
from south.db import db
from south.v2 import DataMigration
from django.db import models
from django.contrib.auth.hashers import make_password

class Migration(DataMigration):

    def forwards(self, orm):
        "Write your forwards methods here."
        # Note: Don't use "from appname.models import ModelName". 
        # Use orm.ModelName to refer to models in this application,
        # and orm['appname.ModelName'] for models in other applications.
        
        orm.Usuario.objects.get_or_create(usuario='AdminMultilingual', password = make_password('LiNgual2014'), nombre='Isis Vanessa Navarro Rivas', is_superuser=True, is_admin=True, email='isis.vane91@gmail.com' )
        orm.Usuario.objects.get_or_create(usuario='multilingual', password = make_password('idiomas2014'), nombre='Multilingual Chihuahua', email='administracion@multilingual.edu.mx' )
        
        orm.Horario.objects.get_or_create(hora="7",verbose_name="7:00-8:00am")
        orm.Horario.objects.get_or_create(hora="8",verbose_name="8:00-9:00am")
        orm.Horario.objects.get_or_create(hora="9",verbose_name="9:00-10:00am")
        orm.Horario.objects.get_or_create(hora="10",verbose_name="10:00-11:00am")
        orm.Horario.objects.get_or_create(hora="11",verbose_name="11:00-12:00pm")
        orm.Horario.objects.get_or_create(hora="12",verbose_name="12:00-01:00pm")
        orm.Horario.objects.get_or_create(hora="13",verbose_name="01:00-02:00pm")
        orm.Horario.objects.get_or_create(hora="14",verbose_name="02:00-03:00pm")
        orm.Horario.objects.get_or_create(hora="15",verbose_name="03:00-04:00pm")
        orm.Horario.objects.get_or_create(hora="16",verbose_name="04:00-05:00pm")
        orm.Horario.objects.get_or_create(hora="17",verbose_name="05:00-06:00pm")
        orm.Horario.objects.get_or_create(hora="18",verbose_name="06:00-07:00pm")
        orm.Horario.objects.get_or_create(hora="19",verbose_name="07:00-08:00pm")
        orm.Horario.objects.get_or_create(hora="20",verbose_name="08:00-09:00pm")
        
        orm.Salon.objects.get_or_create(nombre='PARIS')
        orm.Salon.objects.get_or_create(nombre='DYNAMIC')
        orm.Salon.objects.get_or_create(nombre='BEIJING')
        orm.Salon.objects.get_or_create(nombre='VEGAS')
        orm.Salon.objects.get_or_create(nombre='LONDON')
        orm.Salon.objects.get_or_create(nombre='NEWYORK')
        orm.Salon.objects.get_or_create(nombre='MIAMI')
        orm.Salon.objects.get_or_create(nombre='BIGROOM')
        
        orm.Grupo.objects.get_or_create(nombre='1B', verbose_name='BASICO 1')
        orm.Grupo.objects.get_or_create(nombre='2B', verbose_name='BASICO 2')
        orm.Grupo.objects.get_or_create(nombre='3B', verbose_name='BASICO 3')
        orm.Grupo.objects.get_or_create(nombre='1I', verbose_name='INTERMEDIO 1')
        orm.Grupo.objects.get_or_create(nombre='2I', verbose_name='INTERMEDIO 2')
        orm.Grupo.objects.get_or_create(nombre='3I', verbose_name='INTERMEDIO 3')
        orm.Grupo.objects.get_or_create(nombre='1A', verbose_name='AVANZADO 1')
        orm.Grupo.objects.get_or_create(nombre='2A', verbose_name='AVANZADO 2')
        orm.Grupo.objects.get_or_create(nombre='3A', verbose_name='AVANZADO 3')
        orm.Grupo.objects.get_or_create(nombre='KIDS', verbose_name='KIDS')
        orm.Grupo.objects.get_or_create(nombre='FB', verbose_name='FRANCES BASICO')
        orm.Grupo.objects.get_or_create(nombre='FI', verbose_name='FRANCES INTERMEDIO')
        orm.Grupo.objects.get_or_create(nombre='FA', verbose_name='FRANCES AVANZADO')
        
        orm.Alumno.objects.get_or_create(matricula='295',nombre='DANIEL RAMON VILLANUEVA VALENCIANO')
        orm.Alumno.objects.get_or_create(matricula='934',nombre='RICARDO ZENTENO FRNANDEZ')
        orm.Alumno.objects.get_or_create(matricula='1463',nombre='FERNADA GONZALEZ ERIVES')
        orm.Alumno.objects.get_or_create(matricula='1463B',nombre='ANDREA GONZALEZ ERIVES')
        orm.Alumno.objects.get_or_create(matricula='1491',nombre='JAIME ALEJANDRO JIMENEZ ENRIQUEZ')
        orm.Alumno.objects.get_or_create(matricula='1563',nombre='LUISA GOMEZ MORALES')
        orm.Alumno.objects.get_or_create(matricula='1583',nombre='MARIA VALERIA SAMANIEGO ESPELOSIN')
        orm.Alumno.objects.get_or_create(matricula='1600',nombre='DAVID EDUARDO RAMOS SOTO')
        orm.Alumno.objects.get_or_create(matricula='1605',nombre='ISIDRO MENDOZA BUSTILLOS')
        orm.Alumno.objects.get_or_create(matricula='1607',nombre='FREDDY ANTONIO HERRERA LOPEZ')
        orm.Alumno.objects.get_or_create(matricula='1615',nombre='MA. DEL ROSARIO AYALA SALAS')
        orm.Alumno.objects.get_or_create(matricula='1618',nombre='GERARDO BALDERRAMA OROZCO')
        orm.Alumno.objects.get_or_create(matricula='1635B',nombre='ALEJANDRO VALENCIA SANTOS')
        orm.Alumno.objects.get_or_create(matricula='1643',nombre='CORINA  NAVARRO LOPEZ')
        orm.Alumno.objects.get_or_create(matricula='1649',nombre='CARLOS ALFONSO MORA GUTIERREZ')
        orm.Alumno.objects.get_or_create(matricula='1652',nombre='GABRIELA LOYA RAMIREZ')
        orm.Alumno.objects.get_or_create(matricula='1652B',nombre='NEIBY NOREM LOYA RAMIREZ')
        orm.Alumno.objects.get_or_create(matricula='1658',nombre='LUISA FERNANDA HERNANDEZ MUÑOZ')
        orm.Alumno.objects.get_or_create(matricula='1662',nombre='HORTENCIA HERNANDEZ MONTAÑEZ')
        orm.Alumno.objects.get_or_create(matricula='1662C',nombre='NIDIA HERNANDEZ MONTAÑEZ')
        orm.Alumno.objects.get_or_create(matricula='1664',nombre='MARTHA LETICIA RODRIGUEZ DOMINGUEZ')
        orm.Alumno.objects.get_or_create(matricula='1669',nombre='PAOLA RIVERA GUADERRAMA')
        orm.Alumno.objects.get_or_create(matricula='1670',nombre='VERONICA AGUILAR CONTRERAS')
        orm.Alumno.objects.get_or_create(matricula='1678',nombre='RUBEN HOLGUIN CASTILLO')
        orm.Alumno.objects.get_or_create(matricula='1679',nombre='CESAR ARMANDO HERRERA CUEVAS')
        orm.Alumno.objects.get_or_create(matricula='1710',nombre='VIRIDIANA GALINDO ORTIZ')
        orm.Alumno.objects.get_or_create(matricula='1718',nombre='ARTURO RICO BOVIO')
        orm.Alumno.objects.get_or_create(matricula='1718B',nombre='SYLVIA ANTONIETA JAIME GOMEZ')
        orm.Alumno.objects.get_or_create(matricula='1728',nombre='FABIAN FABRICIO NEVAREZ JIMENEZ')
        orm.Alumno.objects.get_or_create(matricula='1732',nombre='MARIA ESTELA GUTIERREZ ZAPIEN')
        orm.Alumno.objects.get_or_create(matricula='1744',nombre='LOURDES ANDREA ALZAGA GARCIA')
        orm.Alumno.objects.get_or_create(matricula='1744B',nombre='ANA PAULINA GARCIA RAMIREZ')
        orm.Alumno.objects.get_or_create(matricula='1744C',nombre='HECTOR ADRIAN GARCIA RAMIREZ')
        orm.Alumno.objects.get_or_create(matricula='1756',nombre='VIRIDIANA DOMINGUEZ SAENZ')
        orm.Alumno.objects.get_or_create(matricula='1756B',nombre='JESUS ANTONIO MUÑOZ HERRERA')
        orm.Alumno.objects.get_or_create(matricula='1763B',nombre='ADRIANA RAMIREZ CARRILLO')
        orm.Alumno.objects.get_or_create(matricula='1765',nombre='PERLA REBECA RAMOS ORDONO')
        orm.Alumno.objects.get_or_create(matricula='1765B',nombre='GERMAN OCTAVIO RAMOS ORDOÑEZ')
        orm.Alumno.objects.get_or_create(matricula='1770',nombre='RODY ABRAHAM SOTO ROJO')
        orm.Alumno.objects.get_or_create(matricula='1773',nombre='ISLEY YAZMIN BOJORQUEZ APODACA')
        orm.Alumno.objects.get_or_create(matricula='1773B',nombre='DORA ELIA APODACA VILLA')
        orm.Alumno.objects.get_or_create(matricula='1800B',nombre='LIZBETH LOERA MARIÑELARENA')
        orm.Alumno.objects.get_or_create(matricula='1816',nombre='KAREN ALONDRA BELTRAN VERDUGO')
        orm.Alumno.objects.get_or_create(matricula='1826',nombre='AIME HERNANDEZ DOMINGUEZ')
        orm.Alumno.objects.get_or_create(matricula='1831',nombre='ARTURO LARA PEREZ')
        orm.Alumno.objects.get_or_create(matricula='1840',nombre='MORAIMA MARGARITA ECHAVARRIA')
        orm.Alumno.objects.get_or_create(matricula='1852',nombre='FRANCISCO ARMENDARIZ BRISEÑO')
        orm.Alumno.objects.get_or_create(matricula='1866',nombre='OFELIA HERNANDEZ RODRIGUEZ')
        orm.Alumno.objects.get_or_create(matricula='1883B',nombre='JULIO CESAR QUIROZ NUÑEZ')
        orm.Alumno.objects.get_or_create(matricula='1890',nombre='SARAHI VALENZUELA TERRAZAS')
        orm.Alumno.objects.get_or_create(matricula='1896',nombre='SAMANTHA ITZAMARA TARANGO LOPEZ')
        orm.Alumno.objects.get_or_create(matricula='1896B',nombre='JOSE LUIS GOMEZ BAILON')
        orm.Alumno.objects.get_or_create(matricula='1896C',nombre='RITA ANAHI GOMEZ')
        orm.Alumno.objects.get_or_create(matricula='1902',nombre='ASHLEY JAHZIEL MENDOZA G.')
        orm.Alumno.objects.get_or_create(matricula='1919',nombre='MARCOS ELI MELENDEZ VILLA')
        orm.Alumno.objects.get_or_create(matricula='1925',nombre='LAURA LOURDES FIERRO MURILLO')
        orm.Alumno.objects.get_or_create(matricula='1928',nombre='ALEJANDRO GUARDIOLA MENDOZA')
        orm.Alumno.objects.get_or_create(matricula='1938B',nombre='ILSE ASTRID HERNANDEZ VILLALOBOS')
        orm.Alumno.objects.get_or_create(matricula='1940B',nombre='ANA VISTORIA AGUILAR')
        orm.Alumno.objects.get_or_create(matricula='1944A',nombre='MANUEL SALVADOR IRIGOYEN RODRIGUEZ')
        orm.Alumno.objects.get_or_create(matricula='1946',nombre='JOSE URIAS RODRIGUEZ')
        orm.Alumno.objects.get_or_create(matricula='1964',nombre='MAGDA IVETTE CONTRERAS BACA')
        orm.Alumno.objects.get_or_create(matricula='1965',nombre='MAURICIO ARROYO MUÑOZ')
        orm.Alumno.objects.get_or_create(matricula='1967',nombre='MELISSA VIANEY CAMARILLO SANCHEZ')
        orm.Alumno.objects.get_or_create(matricula='1972',nombre='ANA GABRIELA ENRIQUEZ P. ')
        orm.Alumno.objects.get_or_create(matricula='1985B',nombre='MARIA DENISSE ARIAS GOMEZ')
        orm.Alumno.objects.get_or_create(matricula='2017',nombre='JOSE CARLOS ARIAS GOMEZ')
        orm.Alumno.objects.get_or_create(matricula='2036',nombre='RAUL MONTERDE FERNANDEZ')
        orm.Alumno.objects.get_or_create(matricula='2067',nombre='JESUS SIFUENTES VALDEZ')
        orm.Alumno.objects.get_or_create(matricula='2080',nombre='JOSE JUAREZ GARCIA')
        orm.Alumno.objects.get_or_create(matricula='2085',nombre='FRANCISCA JAQUEZ JUAREZ')
        orm.Alumno.objects.get_or_create(matricula='2102',nombre='BERENICE AGUIRRE BECERRA')
        orm.Alumno.objects.get_or_create(matricula='2115',nombre='MIRIAM YAZETH MENDOZA ORONA')
        orm.Alumno.objects.get_or_create(matricula='2117',nombre='ROGELIO ESCOBAR RIVERA')
        orm.Alumno.objects.get_or_create(matricula='2119',nombre='EDGAR CHAVARRIA TRILLO')
        orm.Alumno.objects.get_or_create(matricula='2124',nombre='RODRIGO OCTAVIO GURROLA HUERTA')
        orm.Alumno.objects.get_or_create(matricula='2146',nombre='SANDRA CHAVEZ RODRIGUEZ')
        orm.Alumno.objects.get_or_create(matricula='2160',nombre='SALMA DUARTE BURCIAGA')
        orm.Alumno.objects.get_or_create(matricula='2175',nombre='LEONEL MAGAÑA LOZANO')
        orm.Alumno.objects.get_or_create(matricula='2188',nombre='BENJAMIN AVILA RODRIGUEZ')
        orm.Alumno.objects.get_or_create(matricula='2201',nombre='SUSANA GUARDADO MUÑOZ')
        orm.Alumno.objects.get_or_create(matricula='2202',nombre='FABIAN ORLANDO LUNA LUJAN')
        orm.Alumno.objects.get_or_create(matricula='2206',nombre='JOSE EDUARDO MOLINA CONTRERAS')
        orm.Alumno.objects.get_or_create(matricula='2208',nombre='ALEJANDRA FERNANDEZ REYES')
        orm.Alumno.objects.get_or_create(matricula='2216',nombre='KEVIN FERNANDO TELLEZ SERRANO')
        orm.Alumno.objects.get_or_create(matricula='2236',nombre='JULIO DAVID HERRERA GARCIA')
        orm.Alumno.objects.get_or_create(matricula='2236B',nombre='KATIA MARICELA DE SANTIAGO RODRIGUEZ')
        orm.Alumno.objects.get_or_create(matricula='2249',nombre='GERARDO NAVARIJO LOPEZ')
        orm.Alumno.objects.get_or_create(matricula='2251',nombre='FRANCISCO ARTURO SOTO BAEZ')
        orm.Alumno.objects.get_or_create(matricula='2251B',nombre='ISABEL SARAHI SOTO BAEZ')
        orm.Alumno.objects.get_or_create(matricula='2255',nombre='JUAN DE DIOS GONZALEZ VAZQUEZ')
        orm.Alumno.objects.get_or_create(matricula='2260',nombre='CESAR ALEJANDRO ZAPIEN AZPEITIA')
        orm.Alumno.objects.get_or_create(matricula='2262',nombre='MIGUEL A. DOMINGUEZ SAENZ ')
        orm.Alumno.objects.get_or_create(matricula='2264',nombre='JORGE ALBERTO MALUF SOTO')
        orm.Alumno.objects.get_or_create(matricula='2264B',nombre='SALWA ALEXANDRA MALUF SOTO')
        orm.Alumno.objects.get_or_create(matricula='2268',nombre='LUIS ALONSO MIRANDA RAMIREZ')
        orm.Alumno.objects.get_or_create(matricula='2269',nombre='JOEL GARCIA MALDONADO')
        orm.Alumno.objects.get_or_create(matricula='2270',nombre='LUIS ANGEL RAMIREZ CORRAL')
        orm.Alumno.objects.get_or_create(matricula='2273',nombre='JAZMIN ITZELL CERVANTES DOMINGUEZ')
        orm.Alumno.objects.get_or_create(matricula='2289',nombre='GUSTAVO RODRIGUEZ CABRIALES')
        orm.Alumno.objects.get_or_create(matricula='2300',nombre='ENRIQUE RAMOS ALVAREZ')
        orm.Alumno.objects.get_or_create(matricula='2309',nombre='CARLOS VILLAOBOS PORRAS')
        orm.Alumno.objects.get_or_create(matricula='2323',nombre='DANIELA SANTILLANES PEREZ ANDRADE')
        orm.Alumno.objects.get_or_create(matricula='2327',nombre='JORGE NECOECHEA CAMUÑAS')
        orm.Alumno.objects.get_or_create(matricula='2334',nombre='ALVARO ORTIZ GOMEZ')
        orm.Alumno.objects.get_or_create(matricula='2337',nombre='ARMANDO LUJAN ZAPATA')
        orm.Alumno.objects.get_or_create(matricula='2343',nombre='BLANCA DELIA FLORES LOPEZ')
        orm.Alumno.objects.get_or_create(matricula='2343B',nombre='ANA SOFIA PALACIOS FLORES')
        orm.Alumno.objects.get_or_create(matricula='2346',nombre='FRANCISCO ESTRADA CARDONA')
        orm.Alumno.objects.get_or_create(matricula='2347',nombre='FERNANDO POMPA GUTIERREZ')
        orm.Alumno.objects.get_or_create(matricula='2347B',nombre='ARMANDO POMPA GUTIERREZ')
        orm.Alumno.objects.get_or_create(matricula='2349',nombre='FELIPE DE JESUS MARTINEZ GALVEZ')
        orm.Alumno.objects.get_or_create(matricula='2353',nombre='ALDO STEFFAN SEGURA JIMENEZ')
        orm.Alumno.objects.get_or_create(matricula='2356',nombre='MAYRA DOLORES ALCANTAR FLORES')
        orm.Alumno.objects.get_or_create(matricula='2359',nombre='BEATRIZ ELENA MEDINA QUINTANA')
        orm.Alumno.objects.get_or_create(matricula='2362',nombre='RAQUEL SIAÑEZ SANCHEZ')
        orm.Alumno.objects.get_or_create(matricula='2370',nombre='FERNANDO CRUZ MORALES')
        orm.Alumno.objects.get_or_create(matricula='2370B',nombre='BRENDA YAVELI CRUZ MORALES')
        orm.Alumno.objects.get_or_create(matricula='2372',nombre='HERRERA CORONA JUAN MANUEL')
        orm.Alumno.objects.get_or_create(matricula='2377',nombre='ENRIQUE MENDOZA CARRILLO')
        orm.Alumno.objects.get_or_create(matricula='2382',nombre='ALEJANDRA MUÑOZ ALVARADO')
        orm.Alumno.objects.get_or_create(matricula='2393',nombre='OSCAR IVAN GALLEGOS VILLALBA')
        orm.Alumno.objects.get_or_create(matricula='2394',nombre='ABRIL MARSELLA VIDALES P.')
        orm.Alumno.objects.get_or_create(matricula='2404',nombre='ABDIEL CARREON VILLALOBOS')
        orm.Alumno.objects.get_or_create(matricula='2406',nombre='MARIA MARIBEL JARIZ ESPINO')
        orm.Alumno.objects.get_or_create(matricula='2410',nombre='JULIO ALFONSO RAMIREZ RAZO')
        orm.Alumno.objects.get_or_create(matricula='2425',nombre='ELDA ROSA DOMINGUEZ VILLALBA')
        orm.Alumno.objects.get_or_create(matricula='2431',nombre='DIAZ CHACON CLAUDIA LIZETH')
        orm.Alumno.objects.get_or_create(matricula='2454',nombre='EDGAR ADRIAN DELGADO RODRIGUEZ')
        orm.Alumno.objects.get_or_create(matricula='2455',nombre='JUAN DAVID SOLANO MONREAL ')
        orm.Alumno.objects.get_or_create(matricula='2461',nombre='MARIA CRISTINA MALDONADO O.')
        orm.Alumno.objects.get_or_create(matricula='2475',nombre='MONICA DE LA LUZ ARZAGA VILLASEÑOR')
        orm.Alumno.objects.get_or_create(matricula='2479',nombre='CESAR ADRIAN MEZA RAMOS')
        orm.Alumno.objects.get_or_create(matricula='2482',nombre='CRUZ IVAN PEREZA REYES')
        orm.Alumno.objects.get_or_create(matricula='2483',nombre='JOSE ANTONIO GUERRERO GONZALEZ')
        orm.Alumno.objects.get_or_create(matricula='2489',nombre='VICTOR HUGO ROMERO CORDOVA')
        orm.Alumno.objects.get_or_create(matricula='2496',nombre='JUAN CHAVEZ GONZALEZ')
        orm.Alumno.objects.get_or_create(matricula='2500',nombre='LUZ ELVIA DURAN DE LA CRUZ')
        orm.Alumno.objects.get_or_create(matricula='2505',nombre='CESAR G.LECHUGA MAYNEZ')
        orm.Alumno.objects.get_or_create(matricula='2506',nombre='MARIO IRVIN LEON GODINEZ')
        orm.Alumno.objects.get_or_create(matricula='2507',nombre='LEONARDO LERMA MEDINA')
        orm.Alumno.objects.get_or_create(matricula='2507B',nombre='LIZETH ALEJANDRA LERMA BASURTO')
        orm.Alumno.objects.get_or_create(matricula='2510',nombre='MEGAN PAOLA RUVALCABA JUAREZ')
        orm.Alumno.objects.get_or_create(matricula='2519',nombre='GONZALO ARMANDO LOPEZ GAMEZ')
        orm.Alumno.objects.get_or_create(matricula='2521',nombre='TADEA BELEN ALEJANDRE CARRASCO')
        orm.Alumno.objects.get_or_create(matricula='2522',nombre='DAMARIZ  ZIGRID AGUILAR BOLAÑOS')
        orm.Alumno.objects.get_or_create(matricula='2524',nombre='VANIA VALERIA AGUIRRE JAQUEZ')
        orm.Alumno.objects.get_or_create(matricula='2527',nombre='RAUL TAPIA ALFARO')
        orm.Alumno.objects.get_or_create(matricula='2529',nombre='MANUEL PLIEGO MARTINEZ')
        orm.Alumno.objects.get_or_create(matricula='2532',nombre='JOEL BUSTILLO ACOSTA')
        orm.Alumno.objects.get_or_create(matricula='2535',nombre='YHAZMIN ARIZBETH CHAVARRIA MEZA')
        orm.Alumno.objects.get_or_create(matricula='2540',nombre='LUIS ALBERTO MARQUEZ FLORES')
        orm.Alumno.objects.get_or_create(matricula='2545',nombre='JUAN CARLOS LEORA MENDEZ')
        orm.Alumno.objects.get_or_create(matricula='2547',nombre='SIMONE DE ALMEIDA MIGUEL')
        orm.Alumno.objects.get_or_create(matricula='2550',nombre='IVONNE CERA ANCHONDO')
        orm.Alumno.objects.get_or_create(matricula='2550B',nombre='KATHIA IVONNE LEON CERA')
        orm.Alumno.objects.get_or_create(matricula='2561',nombre='ALAN ISAAC HERNANDEZ ALDAPE')
        orm.Alumno.objects.get_or_create(matricula='2562B',nombre='HUMBERTO NEVAREZ ERIVES')
        orm.Alumno.objects.get_or_create(matricula='2565',nombre='YESSICA RODRIGUEZ GARCIA')
        orm.Alumno.objects.get_or_create(matricula='2566',nombre='RAFAEL SEDANO LOYA')
        orm.Alumno.objects.get_or_create(matricula='2566B',nombre='ANEL IRAIS RODRIGUEZ VILLANUEVA')
        orm.Alumno.objects.get_or_create(matricula='2567',nombre='ALEJANDRA KARINA RAMIREZ')
        orm.Alumno.objects.get_or_create(matricula='2570',nombre='JORGE ALBERTO AVILA ARZOLA')
        orm.Alumno.objects.get_or_create(matricula='2572',nombre='ADRIANA TORRES PAYAN')
        orm.Alumno.objects.get_or_create(matricula='2576',nombre='NOEL FRYLAN NUÑEZ ROMANO')
        orm.Alumno.objects.get_or_create(matricula='2573',nombre='MARIBEL SAENZ LOPEZ')
        orm.Alumno.objects.get_or_create(matricula='2578',nombre='GLORIA YOLANDA RTIVERA CORRAL')
        orm.Alumno.objects.get_or_create(matricula='2579',nombre='SARA JAZMIN GUERRA BOCANEGRA')
        orm.Alumno.objects.get_or_create(matricula='2579B',nombre='ALBERTO DANIEL BOCANEGRA')
        orm.Alumno.objects.get_or_create(matricula='2580',nombre='JAVIER ALONSO CASTELLANOS DOMINGUEZ')
        orm.Alumno.objects.get_or_create(matricula='2580B',nombre='MARGARITA DE LOURDES MUÑOZ RUIZ DE LA PEÑA')
        orm.Alumno.objects.get_or_create(matricula='2581',nombre='ANTONIO MANUEL VILLA ALARCON')
        orm.Alumno.objects.get_or_create(matricula='2582B',nombre='ROGELIO CARRILLO ACOSTA')
        orm.Alumno.objects.get_or_create(matricula='2586',nombre='LUIS CARLOS MAYNEZ')
        orm.Alumno.objects.get_or_create(matricula='2591',nombre='IRVING AARON MARBAN MORALES')
        orm.Alumno.objects.get_or_create(matricula='2593',nombre='DANIEL RODOLFO GRAJEDA LOPEZ')
        orm.Alumno.objects.get_or_create(matricula='2595',nombre='CESAR ARTURO QUINTANA PEÑA')
        orm.Alumno.objects.get_or_create(matricula='2596',nombre='RAMIREZ QUEZADA MONICAJ.')
        orm.Alumno.objects.get_or_create(matricula='2600',nombre='EMMA DEL ROCIO ORTIZ SALINAS')
        orm.Alumno.objects.get_or_create(matricula='2605',nombre='DIANA PAULINA SEPULVEDA OLIVAS')
        orm.Alumno.objects.get_or_create(matricula='2607',nombre='JACQUELINE ENCINAS BELTRAN')
        orm.Alumno.objects.get_or_create(matricula='2608',nombre='GUADALUPE LIZBETH SLGADO ESTRADA')
        orm.Alumno.objects.get_or_create(matricula='2611',nombre='YESENIA RESENDIZ PEREZ')
        orm.Alumno.objects.get_or_create(matricula='2613',nombre='JUAN CARLOS ARANDA NERI')
        orm.Alumno.objects.get_or_create(matricula='2614',nombre='ARTURO RAFAEL SOLIS AGUIRRE')
        orm.Alumno.objects.get_or_create(matricula='2615',nombre='GLORIA ANABEL OCON BAYLON')
        orm.Alumno.objects.get_or_create(matricula='2618',nombre='EMMANUEL RENE PANIAGUA RANGEL')
        orm.Alumno.objects.get_or_create(matricula='2621',nombre='ANDRES ERIVES PEREDA')
        orm.Alumno.objects.get_or_create(matricula='2623',nombre='HECTOR MANUEL PALAFOX ')
        orm.Alumno.objects.get_or_create(matricula='2623B',nombre='OLGA LIBIA URTUZUASTEGUI ')
        orm.Alumno.objects.get_or_create(matricula='2626',nombre='MARIA ELISA CANO SANCHEZ')
        orm.Alumno.objects.get_or_create(matricula='.',nombre='LARIX REBECA ACOSTA ONTIVEROS')
        orm.Alumno.objects.get_or_create(matricula='2630',nombre='JESUS MIGUEL TOVAR FLORES')
        orm.Alumno.objects.get_or_create(matricula='2630B',nombre='SALMA CRISTINA MUELA O.')
        orm.Alumno.objects.get_or_create(matricula='2634',nombre='YOLANDA LIZETH LUJAN MONTOYA')
        orm.Alumno.objects.get_or_create(matricula='2639',nombre='FRANCISCO CARO VELO')
        orm.Alumno.objects.get_or_create(matricula='2642',nombre='EDITH JOHANA OCHOA LOPEZ')
        orm.Alumno.objects.get_or_create(matricula='2647',nombre='ISMAEL FERNANDO HERNANDEZ ACOSTA')
        orm.Alumno.objects.get_or_create(matricula='2650',nombre='ROCIO ALVARADO BALDERRAMA')
        orm.Alumno.objects.get_or_create(matricula='2653B',nombre='ARACELY PARRA ALDAMA')
        orm.Alumno.objects.get_or_create(matricula='2654',nombre='EFREN ENRIQUE PEREDA VILLEZCAS')
        orm.Alumno.objects.get_or_create(matricula='2655',nombre='PEDRO ALONSO PEREDA VILLEZCAS')
        orm.Alumno.objects.get_or_create(matricula='2656',nombre='ABRAHAM PORTILLO BORUNDA')
        orm.Alumno.objects.get_or_create(matricula='2658',nombre='SALOMON DOMINGUEZ ÑUNEZ')
        orm.Alumno.objects.get_or_create(matricula='2660',nombre='OSCAR EDUARDO OROZCO')
        orm.Alumno.objects.get_or_create(matricula='2663',nombre='CRISTOBAL VARGAS CONTRERAS')
        orm.Alumno.objects.get_or_create(matricula='2664',nombre='ANA LETICIA PANDO TREVIZO')
        orm.Alumno.objects.get_or_create(matricula='2664B',nombre='ANA PAULA VALVERDE PANDO')
        orm.Alumno.objects.get_or_create(matricula='2644C',nombre='LUISA FERNANDA VALVERDE PANDO')
        orm.Alumno.objects.get_or_create(matricula='2665',nombre='JULIAN RENTERIA MARQUEZ')
        orm.Alumno.objects.get_or_create(matricula='2666',nombre='MARIANA ALEJANDRA CASTELLANOS AYALA')
        orm.Alumno.objects.get_or_create(matricula='2668',nombre='PAMELA PEREZ VALVERDE')
        orm.Alumno.objects.get_or_create(matricula='2675',nombre='MARIO ANTONIO CHAVEZ CHAVEZ')
        orm.Alumno.objects.get_or_create(matricula='2675B',nombre='FLOR SARAY CHAVEZ CHAVEZ')
        orm.Alumno.objects.get_or_create(matricula='2676',nombre='KARLA IRACEMA NEVAREZ BARAJAS')
        orm.Alumno.objects.get_or_create(matricula='2678',nombre='PATRICIA IVONNE CHAVEZ CHAVEZ')
        orm.Alumno.objects.get_or_create(matricula='2680',nombre='FRANCISCO JAVIER MIRANDA RAMIREZ')
        orm.Alumno.objects.get_or_create(matricula='2682',nombre='ILSE GABRIELA GALLEGOS FLORES')
        orm.Alumno.objects.get_or_create(matricula='2683',nombre='DANIEL EDUARDO CHAVEZ HERNANDEZ')
        orm.Alumno.objects.get_or_create(matricula='2684',nombre='FERNANDA GUIRRE DELGADO')
        orm.Alumno.objects.get_or_create(matricula='2685',nombre='HUGO MANUEL MARTINEZ MARTINEZ')
        orm.Alumno.objects.get_or_create(matricula='2691',nombre='CARLOS ALBERTO RODRÍGUEZ MALDONADO')
        orm.Alumno.objects.get_or_create(matricula='2692',nombre='ANA KAREN MARQUEZ GUERRERO')
        orm.Alumno.objects.get_or_create(matricula='2694',nombre='JORGE LUIS HERRERA HERRERA')
        orm.Alumno.objects.get_or_create(matricula='2695',nombre='FRANCISCO CHACON ROMO')
        orm.Alumno.objects.get_or_create(matricula='2698',nombre='ROMEO ALEJANDRO CARRASCO ALAMILLO')
        orm.Alumno.objects.get_or_create(matricula='2716',nombre='ALEJANDRO DAVID MARTINEZ')
        orm.Alumno.objects.get_or_create(matricula='2716B',nombre='CRISTAL ALEJANDRA MARTINEZ')
        orm.Alumno.objects.get_or_create(matricula='2720',nombre='ROSIO LORENA VALERIO SILVA')
        orm.Alumno.objects.get_or_create(matricula='2720B',nombre='EDUARDO VILLARREAL NUÑEZ')
        orm.Alumno.objects.get_or_create(matricula='2725',nombre='JOSUE RICARDO SANTIAGO MUÑOZ')
        orm.Alumno.objects.get_or_create(matricula='2730',nombre='TANIA VALVERDE MATA')
        orm.Alumno.objects.get_or_create(matricula='2734',nombre='EDEN RAMIREZ GARCIA')
        orm.Alumno.objects.get_or_create(matricula='2739',nombre='MIRNA ALHELI ORNELAS CARAVEO')
        orm.Alumno.objects.get_or_create(matricula='2742',nombre='ROGELIO ARMANDO CHACON NAVARRETE')
        orm.Alumno.objects.get_or_create(matricula='2743',nombre='ALEJANDRO FERNANDEZ FUENTES')
        orm.Alumno.objects.get_or_create(matricula='2743B',nombre='MARTHA ELIZABETH REYES  NAVA2743B')
        orm.Alumno.objects.get_or_create(matricula='2745',nombre='ALFREDO SANDOVAL BERMEO')
        orm.Alumno.objects.get_or_create(matricula='2748',nombre='ADRIAN ARMENDARIZ PEREZ')
        orm.Alumno.objects.get_or_create(matricula='2749',nombre='MARTHA YADIRA ESCOTO ASCENCIO')
        orm.Alumno.objects.get_or_create(matricula='2755',nombre='MARIA MARTHA VALVERDE FLORES')
        orm.Alumno.objects.get_or_create(matricula='2759',nombre='GABRIELA ALEJANDRA HIJAR SOTO')
        orm.Alumno.objects.get_or_create(matricula='2759B',nombre='LORIA EMMA HIJAR SOTO')
        orm.Alumno.objects.get_or_create(matricula='2760',nombre='VICTOR MANUEL CARRILLO RODRIGUEZ')
        orm.Alumno.objects.get_or_create(matricula='2763',nombre='ERNESTO G. TARANGO GONZALEZ')
        orm.Alumno.objects.get_or_create(matricula='2769',nombre='NESTOR SABINO GONZALEZ GARCIA')
        orm.Alumno.objects.get_or_create(matricula='2770',nombre='LUIS ALFREDO RONQUILLO HERNANDEZ')
        orm.Alumno.objects.get_or_create(matricula='2771',nombre='MARIBEL FIGUEROA VALENZUELA ')
        orm.Alumno.objects.get_or_create(matricula='2775',nombre='CRISTINA YASMIN MEDINA REYES')
        orm.Alumno.objects.get_or_create(matricula='2785',nombre='ANA PATRICIA VIYELA ALVARTEZ')
        orm.Alumno.objects.get_or_create(matricula='2785B',nombre='MARIA MARGARITA ALVAREZ TERRAZAS')
        orm.Alumno.objects.get_or_create(matricula='2787',nombre='DIEGO IVAN RODRIGUEZ A.')
        orm.Alumno.objects.get_or_create(matricula='2787B',nombre='ITZE LIZBETH NAVARRO A')
        orm.Alumno.objects.get_or_create(matricula='2788',nombre='MARIO ARON ROSAS TALAMANTES')
        orm.Alumno.objects.get_or_create(matricula='2788B',nombre='ANA LAURA AMBRIZ OROZCO')
        orm.Alumno.objects.get_or_create(matricula='2792',nombre='YECICA YASMIN BACA GARCIA')
        orm.Alumno.objects.get_or_create(matricula='2793',nombre='JOSE ANTONIO PAREDES CEBALLO')
        orm.Alumno.objects.get_or_create(matricula='2794',nombre='CARMEN MUÑOZ AMAYA')
        orm.Alumno.objects.get_or_create(matricula='2799',nombre='LUZ AURORA NUÑEZ CASARES')
        orm.Alumno.objects.get_or_create(matricula='2801',nombre='ALEJANDRA PONCE SANCHEZ')
        orm.Alumno.objects.get_or_create(matricula='2804',nombre='GABRIEL CORONA PEÑA')
        orm.Alumno.objects.get_or_create(matricula='2805',nombre='LAURA ISABEL CABALLERO HERNANDEZ')
        orm.Alumno.objects.get_or_create(matricula='2806',nombre='ANA CRISTINA GUERRERO CASTILLO')
        orm.Alumno.objects.get_or_create(matricula='2807',nombre='JOSE ARMANDO MEZA BERNAL')
        orm.Alumno.objects.get_or_create(matricula='2808',nombre='JANETTE ARRIAGA KEEL')
        orm.Alumno.objects.get_or_create(matricula='2815',nombre='LIZETH MANRIQUEZ OJEDA')
        orm.Alumno.objects.get_or_create(matricula='2816',nombre='GUILLERMO JESUS SALAS MARQUEZ')
        orm.Alumno.objects.get_or_create(matricula='2817',nombre='ANA KAREN TORRES PUGA')
        orm.Alumno.objects.get_or_create(matricula='2819',nombre='KAROL TORRES LOPEZ')
        orm.Alumno.objects.get_or_create(matricula='2820',nombre='LLUVIA ITZAMAR OLAGUE LOPEZ')
        orm.Alumno.objects.get_or_create(matricula='2822',nombre='JOSE CARLOS GONZALEZ SALINAS')
        orm.Alumno.objects.get_or_create(matricula='2823',nombre='JOSE ALFREDO VALLES VARELA')
        orm.Alumno.objects.get_or_create(matricula='2825',nombre='LUIS CARLOS VILLARREAL CARNERO')
        orm.Alumno.objects.get_or_create(matricula='2824',nombre='MARIA DE LOURDES SAENZ ALVARADO')
        orm.Alumno.objects.get_or_create(matricula='2826',nombre='DENISSE GARCIA LEDEZMA')
        orm.Alumno.objects.get_or_create(matricula='2828',nombre='LAURA PATRICIA TORRES GOMEZ')
        orm.Alumno.objects.get_or_create(matricula='2828B',nombre='LUISA FERNANDA TORRES GOMEZ')
        orm.Alumno.objects.get_or_create(matricula='2828C',nombre='MARIA PAULA TORRES GOMEZ')
        orm.Alumno.objects.get_or_create(matricula='2830',nombre='MARCELA ANAHI SEPULVEDA CONTRERAS')
        orm.Alumno.objects.get_or_create(matricula='2834',nombre='LARIZZA MONTOYA RIOS')
        orm.Alumno.objects.get_or_create(matricula='2836',nombre='MYRIAM VALENZUELA ARENIVAR')
        orm.Alumno.objects.get_or_create(matricula='2836B',nombre='MELCHOR ALBERTO LOPEZ ORTIZ')
        orm.Alumno.objects.get_or_create(matricula='2837',nombre='CLAUDIA FLORES MENDOZA')
        orm.Alumno.objects.get_or_create(matricula='2839',nombre='ADRIAN CHAPARRO MONTOYA')
        orm.Alumno.objects.get_or_create(matricula='2840',nombre='IVAN GIOVANNI BARRAGAN LEON')
        orm.Alumno.objects.get_or_create(matricula='2841',nombre='CESAR HUMBERTO ORDUÑO TERRAZAS')
        orm.Alumno.objects.get_or_create(matricula='2844',nombre='MANUEL BELMONTE PALLARES')
        orm.Alumno.objects.get_or_create(matricula='2850',nombre='DANIEL ABRAHAM GARCIA FLORES')
        orm.Alumno.objects.get_or_create(matricula='2857',nombre='MARIA ARMIDA ULATE LUJAN')
        orm.Alumno.objects.get_or_create(matricula='2858',nombre='NORMA ANGELICA GARCIA UGARTE')
        orm.Alumno.objects.get_or_create(matricula='2864',nombre='CYNTHIA SELENE CORONA CASTAÑON')
        orm.Alumno.objects.get_or_create(matricula='2867',nombre='NANCY ORTIZ PALACIOS')
        orm.Alumno.objects.get_or_create(matricula='2868',nombre='ADOLFO MORALES DOMINGUEZ')
        orm.Alumno.objects.get_or_create(matricula='2869',nombre='MARIA ELENA PAREDES HERNANDEZ')
        orm.Alumno.objects.get_or_create(matricula='2870',nombre='ALAN IVAN LOPEZ GUERRERO')
        orm.Alumno.objects.get_or_create(matricula='2873',nombre='VICTOR IBARRA ARELLANO')
        orm.Alumno.objects.get_or_create(matricula='2874',nombre='HUGO ALBERTO ACOSTA HOLGUIN')
        orm.Alumno.objects.get_or_create(matricula='2874B',nombre='JONATHAN ALFONSO SANTAMAN')
        orm.Alumno.objects.get_or_create(matricula='2877',nombre='LUIS ALBERTO RODRIGUEZ GUTIERREZ')
        orm.Alumno.objects.get_or_create(matricula='2882',nombre='OSCAR JAVIER PIÑON GARCIA')
        orm.Alumno.objects.get_or_create(matricula='2883',nombre='OLLIVER ARAGONEZ RIVAS')
        orm.Alumno.objects.get_or_create(matricula='2884',nombre='CARLOS LEMUS RICO')
        orm.Alumno.objects.get_or_create(matricula='2885',nombre='JAVIER GRAJEDA AGUIRRE')
        orm.Alumno.objects.get_or_create(matricula='2886B',nombre='MARIO COVARRUBIAS BALDERRAMA')
        orm.Alumno.objects.get_or_create(matricula='2838',nombre='HECTOR MANUEL VERA SOTO')
        orm.Alumno.objects.get_or_create(matricula='2890',nombre='LUIS ALEJANDRO GONZALEZ ANDRADE')
        orm.Alumno.objects.get_or_create(matricula='2892',nombre='REBECA DEL VALLE JURADO ')
        orm.Alumno.objects.get_or_create(matricula='2896',nombre='JORGE ALFREDO CARRERA ACOSTA ')
        orm.Alumno.objects.get_or_create(matricula='2898',nombre='ANA GABRIELA ACEVEDO CASTRO')
        orm.Alumno.objects.get_or_create(matricula='2899',nombre='LUIS MANUEL LERMA RUIZ')
        orm.Alumno.objects.get_or_create(matricula='2907',nombre='HECTOR RAMON FLORES BERNAL')
        orm.Alumno.objects.get_or_create(matricula='2909',nombre='MERAZ SANCHEZ LLUVIA')
        orm.Alumno.objects.get_or_create(matricula='2918',nombre='MARIANO ZUBIA FRANCO')
        orm.Alumno.objects.get_or_create(matricula='2919',nombre='LISA FERNANDA MEZA FLORES')
        orm.Alumno.objects.get_or_create(matricula='2923',nombre='ISAIS BACA PAYAN')
        orm.Alumno.objects.get_or_create(matricula='2923B',nombre='CINTHIA BERENICE PIÑON PAT')
        orm.Alumno.objects.get_or_create(matricula='2927',nombre='EDUARDO IVAN REYES  SANCHEZ')
        orm.Alumno.objects.get_or_create(matricula='2936',nombre='MARIA CRISTINA MELENDEZ MACIAS')
        orm.Alumno.objects.get_or_create(matricula='2936B',nombre='FABIOLA CRISTINA RAMOS MELENDEZ')
        orm.Alumno.objects.get_or_create(matricula='2941',nombre='ALEXA VALERIA CASTELLANOS ORTIZ')
        orm.Alumno.objects.get_or_create(matricula='2946',nombre='CARLO RODRIGUEZ HERNANDEZ')
        orm.Alumno.objects.get_or_create(matricula='2947',nombre='KARLA JANETH AZAR ESTRADA')
        orm.Alumno.objects.get_or_create(matricula='2949',nombre='IRENE ANDREA FAVILA MONTANA')
        orm.Alumno.objects.get_or_create(matricula='2951',nombre='KARLA SELENE AGUIRRE VALERIO')
        orm.Alumno.objects.get_or_create(matricula='2943',nombre='SARA SOTO TERRAZAS ')
        orm.Alumno.objects.get_or_create(matricula='2958',nombre='ERIKA IVETH HERNANDEZ VAZQUEZ')
        orm.Alumno.objects.get_or_create(matricula='2960',nombre='JESUS JOSE MORENO PEREZ')
        orm.Alumno.objects.get_or_create(matricula='2970',nombre='LUIS DANIEL AGUILAR REYNA')
        orm.Alumno.objects.get_or_create(matricula='2971',nombre='CUEVAS SOSA JOSE MARTIN')
        orm.Alumno.objects.get_or_create(matricula='2972',nombre='EDER EDUARDO RUIZ APODACA')
        orm.Alumno.objects.get_or_create(matricula='2974',nombre='GREGORIO VAZQUEZ OLVERA')
        orm.Alumno.objects.get_or_create(matricula='2979',nombre='ARTURO RAYAL FERNANDEZ')
        orm.Alumno.objects.get_or_create(matricula='2988',nombre='COYNTA BECERRA ARAGONES')
        orm.Alumno.objects.get_or_create(matricula='2995A',nombre='ANAIS FELIX SILVA')
        orm.Alumno.objects.get_or_create(matricula='2995B',nombre='KARINA VILAGRAN HOLGUIN')
        orm.Alumno.objects.get_or_create(matricula='2996',nombre='SILVIA ARACELY BRAVO REALIVAZQUEZ')
        orm.Alumno.objects.get_or_create(matricula='1638',nombre='JAQUELINE MORALES CRUZ')
        orm.Alumno.objects.get_or_create(matricula='1969',nombre='KARLA IVETH MARTINEZ MATA')
        orm.Alumno.objects.get_or_create(matricula='1973',nombre='CLAUDIA GUTIERREZ TORRES')
        orm.Alumno.objects.get_or_create(matricula='2025',nombre='CHANEL KARIME OTERO AMADO')
        orm.Alumno.objects.get_or_create(matricula='2085B',nombre='PAOLA ENVILA JAQUEZ')
        orm.Alumno.objects.get_or_create(matricula='2134',nombre='JESUS LARA RODRIGUEZ')
        orm.Alumno.objects.get_or_create(matricula='2314',nombre='NANCY MARES PORTILLO')
        orm.Alumno.objects.get_or_create(matricula='2350',nombre='ANGEL RUBEN CUERVO MARTINEZ')
        orm.Alumno.objects.get_or_create(matricula='2460',nombre='YARITZA REYES CARBAJAL')
        orm.Alumno.objects.get_or_create(matricula='2523',nombre='VICENTE VIDAL CASTILLO')
        orm.Alumno.objects.get_or_create(matricula='2559',nombre='LESLIE RANGEL TORRES')
        orm.Alumno.objects.get_or_create(matricula='2627',nombre='FRANCISCO SUAREZ MANQUERO')
        orm.Alumno.objects.get_or_create(matricula='2628',nombre='RAYMUNDO NOE CARRILLO PEÑA')
        orm.Alumno.objects.get_or_create(matricula='2634B',nombre='JORGE LUIS LUJAN MONTOYA')
        orm.Alumno.objects.get_or_create(matricula='2640',nombre='ROCIO LOPEZ GARCIA')
        orm.Alumno.objects.get_or_create(matricula='2640B',nombre='SILVIA GARCIA FLORES')
        orm.Alumno.objects.get_or_create(matricula='2640C',nombre='JUAN ENRIQUEZ LOPEZ BARRIO')
        orm.Alumno.objects.get_or_create(matricula='2711',nombre='CARLOS ANTONIO NIETO MARTINEZ')
        orm.Alumno.objects.get_or_create(matricula='2711B',nombre='SUSANA NIETO MARTINEZ')
        orm.Alumno.objects.get_or_create(matricula='2713',nombre='MYRNA DEL CARMEN NAVARRO LIERA')
        orm.Alumno.objects.get_or_create(matricula='2721',nombre='ANA MARIA COREDOVA GARCIA')
        orm.Alumno.objects.get_or_create(matricula='2722',nombre='LIZETH VIRGINIA VILLEGAS RODRIGUEZ')
        orm.Alumno.objects.get_or_create(matricula='2724',nombre='MARIA GUADALUPE ESPINOZA DE AVILA')
        orm.Alumno.objects.get_or_create(matricula='2731',nombre='ELISA ESPERANZA PIZARRO O.')
        orm.Alumno.objects.get_or_create(matricula='2747',nombre='ANDRES FERNANDO AVILA ARMENTA ')
        orm.Alumno.objects.get_or_create(matricula='2780',nombre='JORGE ALBERTO MACIAS FLORES')
        orm.Alumno.objects.get_or_create(matricula='2855',nombre='JAVIER ALEJANDRO JURADO ALVAREZ')
        orm.Alumno.objects.get_or_create(matricula='2855B',nombre='JOYCE ARIADNA BETSABE PEREZ MONTELONGO')
        orm.Alumno.objects.get_or_create(matricula='2877B',nombre='LILIA NOEMI ISLAS JUAREZ')
        orm.Alumno.objects.get_or_create(matricula='2887',nombre='MARIA FIDENCIA SALGADO CENICEROS')
        orm.Alumno.objects.get_or_create(matricula='2917',nombre='PATRICIA D. COVARRUBIAS PADILLA')
        orm.Alumno.objects.get_or_create(matricula='2962',nombre='DAVID PORTILLO CALDERON')
        orm.Alumno.objects.get_or_create(matricula='2213A',nombre='ANDRE CONTRERAS SANCHEZ')
        orm.Alumno.objects.get_or_create(matricula='2213B',nombre='ESAU CONTRERAS SANCHEZ')
        orm.Alumno.objects.get_or_create(matricula='2461B',nombre='MARIA CRISTINA LLERAR M.')
        orm.Alumno.objects.get_or_create(matricula='2564',nombre='ANA LAURA GOMEZ SOLORSANO')
        orm.Alumno.objects.get_or_create(matricula='2564B',nombre='DIANA AIDEE GOMEZ SOLORSANO')
        orm.Alumno.objects.get_or_create(matricula='2585',nombre='EMILIANO AGUIRRE LEORA')
        orm.Alumno.objects.get_or_create(matricula='2585B',nombre='GUILLERMO AGUIRRE LOERA')
        orm.Alumno.objects.get_or_create(matricula='2596B',nombre='JESUS RAMIREZ QUEZADA')
        orm.Alumno.objects.get_or_create(matricula='2605B',nombre='ROCIO LIZETH SEPULVEDA OLIVAS')
        orm.Alumno.objects.get_or_create(matricula='2685B',nombre='MANUEL MARTINEZ MARTINEZ')
        orm.Alumno.objects.get_or_create(matricula='2818',nombre='ALDO DANIEL SOLIS AGUIRRE')
        orm.Alumno.objects.get_or_create(matricula='2847',nombre='BRYAN ALBERTO CALDERON PORTILLO')
        orm.Alumno.objects.get_or_create(matricula='1486',nombre='ANA PATRICIA MONTES DE OCA CAMPOS')
        orm.Alumno.objects.get_or_create(matricula='1502',nombre='SAHID ROGELIO SANDOVAL ALDANA')
        orm.Alumno.objects.get_or_create(matricula='1505',nombre='YAMBILE AMAYNARY DE LA CRUZ ORDAZ')
        orm.Alumno.objects.get_or_create(matricula='1531',nombre='KAREN OLIVIA JIMENEZ RIVERA ')
        orm.Alumno.objects.get_or_create(matricula='1624',nombre='MIGUEL ANGEL HERRERA AHUMADA ')
        orm.Alumno.objects.get_or_create(matricula='1909',nombre='ANA SOFIA GARCIA  RUBIO ')
        orm.Alumno.objects.get_or_create(matricula='2380',nombre='JAVIER ENRIQUEZ SOSA')
        orm.Alumno.objects.get_or_create(matricula='2601',nombre='NATALIA ALCALÁ KUCHLE')
        orm.Alumno.objects.get_or_create(matricula='2786',nombre='CAROLINA HERRERA HURTADO')
        orm.Alumno.objects.get_or_create(matricula='1491',nombre='JAIME ALEJANDRO JIMENEZ ENRIQUEZ')
        orm.Alumno.objects.get_or_create(matricula='1377',nombre='DORIS LOPEZ MUÑOZ')
        orm.Alumno.objects.get_or_create(matricula='1627',nombre='ANTONIO MORENO CHAVIRA')
        orm.Alumno.objects.get_or_create(matricula='1633',nombre='SELENE LOZOYA LOZOYA')
        orm.Alumno.objects.get_or_create(matricula='1686',nombre='ANNA DARYNA MORALES MARTINEZ')
        orm.Alumno.objects.get_or_create(matricula='1703',nombre='ROXANA BERENICE PALLARES SAMANO')
        orm.Alumno.objects.get_or_create(matricula='1710',nombre='VIRIDIANA GALINDO ORTIZ')
        orm.Alumno.objects.get_or_create(matricula='1755',nombre='CARLA MARIA SOTO QUEZADA')
        orm.Alumno.objects.get_or_create(matricula='1763',nombre='KAREN LIZBETH TINAJERO VILLALOBOS')
        orm.Alumno.objects.get_or_create(matricula='1944',nombre='CARLOS ARTURO GABALDON RAMIREZ')
        orm.Alumno.objects.get_or_create(matricula='1826B',nombre='ALEJANDRA HERNANDEZ DOMINGUEZ')
        orm.Alumno.objects.get_or_create(matricula='1841',nombre='DANIEL CORTESZ SIAÑEZ')
        orm.Alumno.objects.get_or_create(matricula='1844B',nombre='EVA CAROLINA YAÑEZ VARGAS')
        orm.Alumno.objects.get_or_create(matricula='1844C',nombre='AYLIN YARELI GABALDON YAÑEZ')
        orm.Alumno.objects.get_or_create(matricula='1844D',nombre='BRANDON ALEXIS GABALDON YAÑEZ')
        orm.Alumno.objects.get_or_create(matricula='1847',nombre='DAMARIS GONZALEZ M.')
        orm.Alumno.objects.get_or_create(matricula='1847B',nombre='EDUARDO TREJO PEÑA')
        orm.Alumno.objects.get_or_create(matricula='1861',nombre='ALFONSO IBARRA BUSTILLOS')
        orm.Alumno.objects.get_or_create(matricula='1875',nombre='JOSE LUIS MUÑOZ PEREZ')
        orm.Alumno.objects.get_or_create(matricula='1890',nombre='SARAHI VALENZUELA TERRAZAS')
        orm.Alumno.objects.get_or_create(matricula='1921',nombre='LUIS ARTURO REYES MARQUEZ')
        orm.Alumno.objects.get_or_create(matricula='1923',nombre='ELEAZAR AMIN OLVERA')
        orm.Alumno.objects.get_or_create(matricula='1927',nombre='LUCIA MOLINA CORDOVA')
        orm.Alumno.objects.get_or_create(matricula='1931',nombre='GRISEL A. RUIZ SALAZAR')
        orm.Alumno.objects.get_or_create(matricula='1934',nombre='SANDRA PATRICIA HERNANDEZ PEREZ')
        orm.Alumno.objects.get_or_create(matricula='1937',nombre='LUIS ANDRES BURROLA GANDARA')
        orm.Alumno.objects.get_or_create(matricula='1944B',nombre='RUBEN MARTINEZ PONCE')
        orm.Alumno.objects.get_or_create(matricula='1950',nombre='JESUS IVAN CARO RASCON')
        orm.Alumno.objects.get_or_create(matricula='1968',nombre='KAREN VALLES ESCOBAR')
        orm.Alumno.objects.get_or_create(matricula='1999',nombre='LUIS MARIO SANCHEZ RUBIO')
        orm.Alumno.objects.get_or_create(matricula='2029',nombre='RUIZ RODRIGUEZ MARIA GUADALUPE')
        orm.Alumno.objects.get_or_create(matricula='2058',nombre='MARLEN JUDITH PAEZ CASTILLO')
        orm.Alumno.objects.get_or_create(matricula='2060',nombre='BLANCA ELIZABETH MONARREZ C.')
        orm.Alumno.objects.get_or_create(matricula='2119',nombre='EDGAR CHAVARRIA TRILLO')
        orm.Alumno.objects.get_or_create(matricula='2177',nombre='EDGAR OMAR BUSTILLOS MONTELONGO ')
        orm.Alumno.objects.get_or_create(matricula='2206B',nombre='ELIZABETH MINJAREZ HERNANDEZ')
        orm.Alumno.objects.get_or_create(matricula='2213',nombre='ELIZABETH SANCHEZ LOPEZ')
        orm.Alumno.objects.get_or_create(matricula='2219',nombre='VARELA MOLINAR MARIA ELENA')
        orm.Alumno.objects.get_or_create(matricula='2246',nombre='LAURA ESTELA VILLALBA ASTORGA')
        orm.Alumno.objects.get_or_create(matricula='2246C',nombre='JOSE BENJAMIN AGUILAR VILLALBA')
        orm.Alumno.objects.get_or_create(matricula='2246B',nombre='LAURA YAZMIN AGUILAR VILLANUEVA')
        orm.Alumno.objects.get_or_create(matricula='2250',nombre='BRANDO FERNANDEZ CASTILLO')
        orm.Alumno.objects.get_or_create(matricula='2288',nombre='MARIO FCO. TORRES JAVALERA')
        orm.Alumno.objects.get_or_create(matricula='2288B',nombre='CITLALITL CASTAÑEDA CHAVIRA')
        orm.Alumno.objects.get_or_create(matricula='2288C',nombre='DANIEL NUÑEZ CASILLAS')
        orm.Alumno.objects.get_or_create(matricula='2322',nombre='DANIELA ALEJANDRA RUIZ HERNANDEZ')
        orm.Alumno.objects.get_or_create(matricula='2320',nombre='ALEJANDRA RODRIGUEZ GUZMAN')
        orm.Alumno.objects.get_or_create(matricula='2339',nombre='CESAR ORTIZ RODRIGUEZ')
        orm.Alumno.objects.get_or_create(matricula='2362',nombre='RAQUEL SIAÑEZ SANCHEZ')
        orm.Alumno.objects.get_or_create(matricula='2553',nombre='JAVIER NAHUM LOPEZ AVILA')
        orm.Alumno.objects.get_or_create(matricula='2799',nombre='LUZ AURORA NUÑEZ CASARES')
        orm.Alumno.objects.get_or_create(matricula='2345',nombre='PALOMA INES DE J. RUIZ RODRIGUEZ')
        orm.Alumno.objects.get_or_create(matricula='2570',nombre='JORGE ALBERTO AVILA ARZOLA')
        orm.Alumno.objects.get_or_create(matricula='2525',nombre='LUIS RAUL MADERO GONZALEZ')
        orm.Alumno.objects.get_or_create(matricula='2685C',nombre='ITZEL ADILENE MARTINEZ MARTINEZ')
        orm.Alumno.objects.get_or_create(matricula='2732',nombre='MIGUEL ANGEL IBARRA JUAREZ')
        orm.Alumno.objects.get_or_create(matricula='2728',nombre='MARIA TERESA TERRAZAS BAEZA')
        orm.Alumno.objects.get_or_create(matricula='2906',nombre='JOSE RAMON MARTINEZ DOMINGUEZ')
        orm.Alumno.objects.get_or_create(matricula='2842',nombre='OMAR FERNANDO PAEZ PEÑA')
        orm.Alumno.objects.get_or_create(matricula='2865',nombre='ELIZABETH LUJAN RIOS')
        orm.Alumno.objects.get_or_create(matricula='1689',nombre='ARGELIA SARAHI GRAIJALVA MUÑOZ')
        orm.Alumno.objects.get_or_create(matricula='1792',nombre='ENRIQUE ASUNSOLO MORALES')
        orm.Alumno.objects.get_or_create(matricula='1834',nombre='JOSE ANTONIO SIGALA ROCHIN')
        orm.Alumno.objects.get_or_create(matricula='2138',nombre='ITZEL NALLELY VILLA GASTELUM')
        orm.Alumno.objects.get_or_create(matricula='2534',nombre='DALIA HERNANDEZ VALLES')
        orm.Alumno.objects.get_or_create(matricula='2878',nombre='JESICA LETICIA AQUINO LOPEZ')
        orm.Alumno.objects.get_or_create(matricula='1489',nombre='IVAN ALBERTO RAMIREZ OROZCO')
        orm.Alumno.objects.get_or_create(matricula='2562',nombre='ARNOLDO ERIVEZ RODRIGUEZ')
        orm.Alumno.objects.get_or_create(matricula='2963',nombre='AMANDA MIROSLAVA MUÑIZ BORUNDA')
        orm.Alumno.objects.get_or_create(matricula='2200',nombre='JOSE ANTONIO PULIDO SUAREZ')
        orm.Alumno.objects.get_or_create(matricula='2784',nombre='MOROSLAVA REYES ANCHONDO')
        orm.Alumno.objects.get_or_create(matricula='2407',nombre='JESUS ARNOLDO RUIZ CAMPOS')
        orm.Alumno.objects.get_or_create(matricula='2044',nombre='JESUS EDUARDO REYES GUTIERREZ')
        orm.Alumno.objects.get_or_create(matricula='2530',nombre='ITZEL ALEJANDRA LUGO GONZALEZ')
        orm.Alumno.objects.get_or_create(matricula='2751',nombre='JORGE SALAYANDIA RODRIGUEZ')
        orm.Alumno.objects.get_or_create(matricula='2364',nombre='STHEPANIE GOMEZ PAYAN')
        orm.Alumno.objects.get_or_create(matricula='2598',nombre='KAREN FERNANDA ZAMBRANO LARA')
        orm.Alumno.objects.get_or_create(matricula='581',nombre='ANGELICA LOWEN PACHECO')
        orm.Alumno.objects.get_or_create(matricula='595',nombre='VICTOR HUGO GUILLEN LOPEZ')
        orm.Alumno.objects.get_or_create(matricula='662',nombre='MYRIAM REBECA MARQUEZ CHAVEZ')
        orm.Alumno.objects.get_or_create(matricula='778',nombre='DIEGO ARMANDO MIRANDA OROZCO')
        orm.Alumno.objects.get_or_create(matricula='823',nombre='JOSE ANGEL BAUTISTA SANZ')
        orm.Alumno.objects.get_or_create(matricula='1269',nombre='FRIDA PRISCILA VALDENEA GUILLEN')
        orm.Alumno.objects.get_or_create(matricula='740B',nombre='JUAN CARLOS MENDOZA VILLALOBOS')
        orm.Alumno.objects.get_or_create(matricula='1442',nombre='LUIS RICARDO MARTÍNEZ ALMODOVAR')
        orm.Alumno.objects.get_or_create(matricula='1507',nombre='MIRIAM CRISTINA FLORES MENA')
        orm.Alumno.objects.get_or_create(matricula='1533',nombre='JORGE LUIS CHAVIRA RODELO')
        orm.Alumno.objects.get_or_create(matricula='1535',nombre='BLANCA LILIANA LEYVA LUCERO')
        orm.Alumno.objects.get_or_create(matricula='1542',nombre='TANIA JAQUEZ ARZAGA')
        orm.Alumno.objects.get_or_create(matricula='1547',nombre='NYDIA MENDOZA QUINTANA')
        orm.Alumno.objects.get_or_create(matricula='1547B',nombre='NUBIA LUZ MENDOZA QUINTANA')
        orm.Alumno.objects.get_or_create(matricula='1598',nombre='JESUS ARTURO PEREYRA RIOS')
        orm.Alumno.objects.get_or_create(matricula='1424',nombre='CARMEN YAJAIRA BAYONA VALDEZ')
        orm.Alumno.objects.get_or_create(matricula='1787',nombre='OSCAR MADRID ESTRADA')
        orm.Alumno.objects.get_or_create(matricula='2926',nombre='ALVARADO GRANADINO JESUS ARTURO')
        orm.Alumno.objects.get_or_create(matricula='3011',nombre='BETANCOURTH RODRIGUEZ JESUS ELIGIO')
        orm.Alumno.objects.get_or_create(matricula='2959',nombre='CASAS GARCIA LAURA GUADALUPE')
        orm.Alumno.objects.get_or_create(matricula='2439',nombre='CARMONA GONZALEZ JORGE EZEQUIEL')
        orm.Alumno.objects.get_or_create(matricula='2439B',nombre='CARMONA GONZALEZ IRAM VICENTE')
        orm.Alumno.objects.get_or_create(matricula='3030',nombre='CHAVEZ DIAZ MARIA FERNANDA')
        orm.Alumno.objects.get_or_create(matricula='2851',nombre='DIAZ GOMEZ BLANCA ROSA')
        orm.Alumno.objects.get_or_create(matricula='2416',nombre='ESCOBAR CHIRINO GABRIEL')
        orm.Alumno.objects.get_or_create(matricula='2982',nombre='FERNANDEZ LUNA FABIOLA EDITH')
        orm.Alumno.objects.get_or_create(matricula='2995C',nombre='FELIX SILVA ANAIS')
        orm.Alumno.objects.get_or_create(matricula='2430',nombre='GARCIA RUIZ VERONICA')
        orm.Alumno.objects.get_or_create(matricula='2402',nombre='GARCIA VALLES JESUS FRANCISCO')
        orm.Alumno.objects.get_or_create(matricula='2416B',nombre='GOMEZ GRISELDA RUBI')
        orm.Alumno.objects.get_or_create(matricula='2432',nombre='GUERRA MENDIAS NORBERTO')
        orm.Alumno.objects.get_or_create(matricula='2944',nombre='HERNANDEZ RIVERO MIRIAM')
        orm.Alumno.objects.get_or_create(matricula='2409',nombre='IRUTTALDE GALV AN FLOR GISEL')
        orm.Alumno.objects.get_or_create(matricula='3019',nombre='JUAREZ FERNANDEZ ADRIAN')
        orm.Alumno.objects.get_or_create(matricula='2417',nombre='LERMA CABRERA ANDREA GIOVANNA')
        orm.Alumno.objects.get_or_create(matricula='2418',nombre='LERMA CABRERA BIANCA ESTELA')
        orm.Alumno.objects.get_or_create(matricula='2449',nombre='MARQUEZ CISNEROS BLANCA ISELA')
        orm.Alumno.objects.get_or_create(matricula='3017',nombre='MARQUEZ GRAJEDA ISMAEL')
        orm.Alumno.objects.get_or_create(matricula='3007',nombre='MEDINA RAMIREZ JESUS ALBERTO')
        orm.Alumno.objects.get_or_create(matricula='3003',nombre='MENDEZ JOSELINE ANGEL')
        orm.Alumno.objects.get_or_create(matricula='3012',nombre='MONTANA LICON LUCILA ')
        orm.Alumno.objects.get_or_create(matricula='3001',nombre='MOTA ADAME LUIS BERNABE')
        orm.Alumno.objects.get_or_create(matricula='3001A',nombre='MOTA ADAME ALBE ALICIA')
        orm.Alumno.objects.get_or_create(matricula='2916B',nombre='MUÑOZ CASTELLANOS VERA LILIAN')
        orm.Alumno.objects.get_or_create(matricula='2433',nombre='NUÑEZ CARO ALDO ')
        orm.Alumno.objects.get_or_create(matricula='2447',nombre='PONCE MIRANDA OSIEL')
        orm.Alumno.objects.get_or_create(matricula='2984',nombre='QUINTANA GUTIERREZ JESUS MANUEL')
        orm.Alumno.objects.get_or_create(matricula='2933',nombre='RABELO ESQUIVEL ADA KARINA')
        orm.Alumno.objects.get_or_create(matricula='3027',nombre='ROJA AMARO JOSE GUADALUPE')
        orm.Alumno.objects.get_or_create(matricula='2442',nombre='SOLIS MELENDEZ JORGE ARTURO')
        orm.Alumno.objects.get_or_create(matricula='2916',nombre='TERAN DOMINGUEZ MARGARITA')
        orm.Alumno.objects.get_or_create(matricula='2440',nombre='VALERIO RODRIGUEZ SUSANA')
        orm.Alumno.objects.get_or_create(matricula='3009',nombre='ZUQUI RAMIREZ MIGUEL ANGEL')
        orm.Alumno.objects.get_or_create(matricula='2994',nombre='CARNERO VITOLAS DIANA IMELDA')
        
    def backwards(self, orm):
        "Write your backwards methods here."
        orm.Usuario.objects.all().delete()
        orm.Alumnos.objects.all().delete()
        orm.Grupo.objects.all().delete()
        orm.Horario.objects.all().delete()
        orm.Salon.objects.all().delete()

    models = {
        u'auth.group': {
            'Meta': {'object_name': 'Group'},
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '80'}),
            'permissions': ('django.db.models.fields.related.ManyToManyField', [], {'to': u"orm['auth.Permission']", 'symmetrical': 'False', 'blank': 'True'})
        },
        u'auth.permission': {
            'Meta': {'ordering': "(u'content_type__app_label', u'content_type__model', u'codename')", 'unique_together': "((u'content_type', u'codename'),)", 'object_name': 'Permission'},
            'codename': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'content_type': ('django.db.models.fields.related.ForeignKey', [], {'to': u"orm['contenttypes.ContentType']"}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '50'})
        },
        u'contenttypes.contenttype': {
            'Meta': {'ordering': "('name',)", 'unique_together': "(('app_label', 'model'),)", 'object_name': 'ContentType', 'db_table': "'django_content_type'"},
            'app_label': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'model': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '100'})
        },
        'horarios.alumno': {
            'Meta': {'object_name': 'Alumno'},
            'fecha': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'matricula': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '20'}),
            'nombre': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '60', 'db_index': 'True'})
        },
        'horarios.alumnosclase': {
            'Meta': {'unique_together': "(['usuario', 'clase'],)", 'object_name': 'AlumnosClase'},
            'clase': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'alumnos'", 'to': "orm['horarios.Clase']"}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'usuario': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'clases'", 'to': "orm['horarios.Alumno']"})
        },
        'horarios.clase': {
            'Meta': {'unique_together': "(['hora', 'salon', 'fecha'],)", 'object_name': 'Clase'},
            'estatus': ('django.db.models.fields.CharField', [], {'default': "'activa'", 'max_length': '20'}),
            'fecha': ('django.db.models.fields.DateField', [], {}),
            'grupo': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'clases'", 'to': "orm['horarios.Grupo']"}),
            'hora': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'clases'", 'to': "orm['horarios.Horario']"}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'salon': ('django.db.models.fields.related.ForeignKey', [], {'related_name': "'clases'", 'to': "orm['horarios.Salon']"})
        },
        'horarios.grupo': {
            'Meta': {'object_name': 'Grupo'},
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'nombre': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '10', 'db_index': 'True'}),
            'verbose_name': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '40', 'db_index': 'True'})
        },
        'horarios.horario': {
            'Meta': {'object_name': 'Horario'},
            'hora': ('django.db.models.fields.CharField', [], {'max_length': '10'}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'verbose_name': ('django.db.models.fields.CharField', [], {'max_length': '50'})
        },
        'horarios.salon': {
            'Meta': {'object_name': 'Salon'},
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'nombre': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '30', 'db_index': 'True'})
        },
        'horarios.usuario': {
            'Meta': {'object_name': 'Usuario'},
            'apellidos': ('django.db.models.fields.CharField', [], {'max_length': '100', 'null': 'True', 'blank': 'True'}),
            'email': ('django.db.models.fields.EmailField', [], {'max_length': '50', 'null': 'True', 'blank': 'True'}),
            'fecha': ('django.db.models.fields.DateTimeField', [], {'auto_now_add': 'True', 'blank': 'True'}),
            'fecha_mod': ('django.db.models.fields.DateTimeField', [], {'auto_now': 'True', 'blank': 'True'}),
            'groups': ('django.db.models.fields.related.ManyToManyField', [], {'symmetrical': 'False', 'related_name': "u'user_set'", 'blank': 'True', 'to': u"orm['auth.Group']"}),
            u'id': ('django.db.models.fields.AutoField', [], {'primary_key': 'True'}),
            'is_active': ('django.db.models.fields.BooleanField', [], {'default': 'True'}),
            'is_admin': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'is_superuser': ('django.db.models.fields.BooleanField', [], {'default': 'False'}),
            'last_login': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now'}),
            'nombre': ('django.db.models.fields.CharField', [], {'max_length': '100'}),
            'password': ('django.db.models.fields.CharField', [], {'max_length': '128'}),
            'user_permissions': ('django.db.models.fields.related.ManyToManyField', [], {'symmetrical': 'False', 'related_name': "u'user_set'", 'blank': 'True', 'to': u"orm['auth.Permission']"}),
            'usuario': ('django.db.models.fields.CharField', [], {'unique': 'True', 'max_length': '30', 'db_index': 'True'})
        }
    }

    complete_apps = ['horarios']
    symmetrical = True
